### ISSUE TITLE
Using post scanlines causes rendering issues on Mac OS X

### ISSUE THREAD

**Issue by patchfx** [thebracket/rltk_rs#54] opened 2020-01-25 11:14 UTC
The latest RLTK 0.6 has a rendering issue when using post scanlines.

Without `context.with_post_scanlines(true)`
![Jan-25-2020 11-08-05](https://user-images.githubusercontent.com/294376/73120231-7b3b0880-3f63-11ea-82e4-dff2ddc532c0.gif)

With `context.with_post_scanlines(true)`
![Jan-25-2020 11-09-21](https://user-images.githubusercontent.com/294376/73120241-8ee66f00-3f63-11ea-802a-843950be0fa1.gif)

Not sure if related to the changes made in #46 ?

RLTK: 0.6

**Comment by thebracket** [comment] 2020-01-25 15:29
Oh! I see what happened: the scanlines shader takes the screen size as a parameter (GL didn't support retrieving it directly in older versions), and it looks like I forgot to update that to take DPI into account. I'll try and get it fixed in the next release - thanks!

**Comment by thebracket** [comment] 2020-01-28 14:37
I've confirmed that you can trigger this with Windows DPI scaling also. Looking for a solution.

**Comment by thebracket** [comment] 2020-01-28 15:00
The linked patch fixes it on Windows, would you mind giving it a go on Mac? (You may have to rename the "serialization" feature to "serde", and "ecs" to "specs" if you are using them; I just applied a PR that does that in the name of complying with standards, the tutorial will be updated to match when I publish the crate).

**Comment by patchfx** [comment] 2020-01-28 15:53
Can confirm that is now fixed, from the latest master branch 👍 

<img width="639" alt="Screenshot 2020-01-28 at 15 52 16" src="https://user-images.githubusercontent.com/294376/73280349-48547700-41e6-11ea-9074-1c45922f4368.png">

**Comment by thebracket** [comment] 2020-01-28 16:21
Awesome, thank you! I'll push out a 0.6.1 as soon as I've caught up with some other issues in the tutorial.

**Closed** 2020-01-28 16:21 UTC
Labels: awaiting_confirmation, bug
