### ISSUE TITLE
Window size changes multiple times per second and other problems under Wayland

### ISSUE THREAD

**Issue by mgedmin** [thebracket/rltk_rs#6] opened 2019-09-13 14:25 UTC
I'm trying to run the examples from  https://github.com/thebracket/rustrogueliketutorial on Ubuntu 19.04, in a Wayland session, using rustc 1.37.0.

When I `cargo run` any of the examples (except the hello world one), the opened window keeps changing its size multiple times per second (once every frame perhaps?).  The contents of the window shift up and down, the topmost few rows of tiles briefly hiding under the title bar, which might be A Clue?

I was also building Firefox in the background, which may have had an effect.  Now that the Firefox build stopped, I can no longer reproduce the window size changes, but I've a different problem instead -- the built program is eating 100% CPU and ignoring all input events.  I can't even close the window, I have to ^C in the console.

(Input worked when I was testing earlier, although in a jerky fashion -- it seemed like some of my key up/down events were being dropped, leading to the @ standing still while I was trying to move it, or sometimes running until it hit a wall despite me just briefly pressing and releasing an arrow key.)

**Comment by thebracket** [comment] 2019-09-13 15:32
I'll see if I can get a Linux VM going to test this. I'm writing on Windows, which tends to either work or not work spectacularly! I mostly do server-side Linux work, so it may take me a bit to get caught up on this one.
Thanks for letting me know!

**Comment by vks** [comment] 2019-09-16 12:54
I also have this problem on Linux (without Wayland). It seems to be related to window decorations. They appear later than the rest of the window, and the jumps correspond to the size of the window decorations.

**Comment by thebracket** [comment] 2019-09-16 13:26
Still trying to get a VM up and running (I'm really low on disk space!), but I suspect that the issue is in `rltk.rs`, specifically the lines:

```rust
WindowEvent::Resized(logical_size) => {
                    let dpi_factor = wc.window().hidpi_factor();
                    wc.resize(logical_size.to_physical(dpi_factor));
                }
```

So every time the console receives an update command, it tries to adjust the physical size to handle the logical size (this was from some example code). Commenting it out on Windows doesn't change anything (I think it's an attempt to work around Mac's odd resolution handling), but would mean that the "resize" event sent by the Linux system to handle the addition of window decorations wouldn't trigger a resize (which in turn seems to trigger another resize).

So I'll commit a version that comments this out - any chance one of you could update and give it a go for me, please? I'll keep trying on the VM...

**Comment by vks** [comment] 2019-09-16 15:00
This does fix the issue for me!

**Comment by thebracket** [comment] 2019-09-16 15:28
I'll wait to make sure I haven't caused problems anywhere before I close it, but hopefully that'll do it.

**Comment by mgedmin** [comment] 2019-09-16 17:41
I'll open a separate bug for my input issues.

**Comment by vks** [comment] 2019-09-16 19:20
I also have the input issues you describe. They persist after the fix for
the flickering.

**Comment by mgedmin** [comment] 2019-09-17 06:30
This seems to be fixed for me with the latest rltk_rs.

**Comment by thebracket** [comment] 2019-09-18 18:51
Appears to be fixed.

**Closed by thebracket** 2019-09-18 18:51 UTC
Labels: bug
